let addition = '';

// ... bunch of code tho ...
// ... bunch of code tho ...
// ... bunch of code tho ...
// ... bunch of code tho ...
// ... bunch of code tho ...
// ... bunch of code tho ...
// ... bunch of code tho ...
// ... bunch of code tho ...

/*
    a pure function is one that does NOT
    rely on any outside variables

    generally relying on outside variables WORK
    however, can be dangerous and the function is
    no longer a black box
*/
function myAge(ageNow, numYears) {

    let addition = ageNow + numYears;

    return addition; 
}
